### ISSUE TITLE
SNS doesn't send code

### ISSUE THREAD

**Issue by dshilovprpl** [casdoor/go-sms-sender#36]
My template: "Your code: %s"

Actual Result: "Your code: %s"

Expected result: "Your code: 123456", if code is 123456

I think here should be smth like it is on twilio:

```go
        code, ok := param["code"]
	if !ok {
		return fmt.Errorf("missing parameter: msg code")
	}
	var err error

	bodyContent := fmt.Sprintf(c.template, code)
```

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/go-sms-sender/commit/9195708d299c7a828245e8e87a9a2c26b9f70a38

Casdoor will release new version for: https://github.com/casbin/casdoor/commit/698f24f7622ba9bd507835b8a5cc7ff819996177
