### ISSUE TITLE
Add VAPTCHA SMS provider

### ISSUE THREAD

**Issue by launchpad001** [casdoor/go-sms-sender#47]
https://www.vaptcha.com/document/install.html#%E7%9F%AD%E4%BF%A1%E6%8E%A5%E5%8F%A3

**Comment by hsluoyz** [comment]
@rdp-studio can you make a PR to support it?

**Comment by launchpad001** [comment]
> @rdp-studio can you make a PR to support it?

Yes, but I need some time.

**Comment by hsluoyz** [comment]
OK, take your time. This issue will be closed for now.
